### ISSUE TITLE
t-shirt, stickers. 

### ISSUE THREAD

**Issue by Jadergomes** [devsgroup/projects#2]
Então, eu já tinha comentado isso uma vez no grupo, assim como outras pessoas também, de vestir a camisa literalmente. Estou apenas deixando registrado aqui nesse espaço idealizado pelo @YanMagale,  essa ideia que seria fazermos t-shirts, stickers com a logo do nosso grupo. Eu tenho convicção que esse grupo dará muitas alegrias individual e coletivamente. :)

**Comment by gabrielazevedo** [comment]
Concordo @JaderGJ ficaria muito show!
Nosso grupo está crescendo a cada dia :)

**Comment by YanMagale** [comment]
Muito boa ideia @JaderGJ . Podemos começar a olhar possíveis empresas para a confecção das camisas e de uma gráfica para fazer os stickers.....alguém conhece ou pode indicar alguma ?

@lucasmaiaesilva  Poderia fazer a arte da camisa ou dos stickers pra nós em ;)

**Comment by JaderGJ** [comment]
Conheço sim cara, aqui em Salvador tem o Lauro (orginazador do front in bahia) que faz os stickers. http://www.stickersdevs.com.br/stickers-personalizados/

- Por sinal foi ele que fez os stickers pra area de software aqui do SENAI.

**Comment by YanMagale** [comment]
Shoow entao em @JaderGJ , você pode olhar com ele pra quente a questão do preço e a quantidade mínima de stickers para impressão ???

**Comment by JaderGJ** [comment]
Super posso, acho que a questão mesmo vai ser o da arte/file da logo. Como eu tinha dito anteriormente, a logo que está na organização foi um recorte que eu fiz do original feito pelo @lucasmaiaesilva, e acho que ele não possui mais esse arquivo. Aí tem que fazer uma outra logo quem manjar dos paranauês!

**Comment by YanMagale** [comment]
Blza então cara ... @lucasmaiaesilva  vc tem o arquivo original da logo ?


E o resto da galera, topam fazer os stickers ??

**Comment by tiagoporto** [comment]
A logo vai ser essa mesmo? Não é difícil para vetorizar.

**Comment by YanMagale** [comment]
Por mim, tranquilo ....

**Comment by JaderGJ** [comment]
De boa, a logo é só as iniciais do grupo mesmo (DG).

**Comment by YanMagale** [comment]
Então agora é ver com o restante da galera, para podermos colher o $$ e fazer o pedido.

**Comment by tiagoporto** [comment]
Até a noite se não tiverem achado o arquivo eu vetorizo a logo de boa.

**Comment by YanMagale** [comment]
Show .... @tiagoporto rola de vc olhar as camisas pra gente, com aquele conhecido seu ??

**Comment by tiagoporto** [comment]
Cara, eu cheguei a fazer um orçamento mas era de camisa bordada. Essa vai ser bordada ou impressa?

**Comment by brunopulis** [comment]
Então pessoal na minha opinião acho bem massa isso, mas esse tipo de decisão acho conveniente fazermos internamente. Sugeri usarmos o slack para resolvermos estas questões.

**Comment by brunopulis** [comment]
@tiagoporto Eu tenho um contato lá de SP pra camisas e a mesma empresa que fez as do Minas Dev

**Comment by YanMagale** [comment]
Show entao @brunopulis ... Vamos criar o slack e decidir esta issue lá.

**Comment by YanMagale** [comment]
Galera, criei o slack pra nossa organizaçaõ (https://devsgroup.slack.com/)

Postem seus e-mails para eu add lá no slack.

**Comment by JaderGJ** [comment]
jadergomes20@gmail.com

**Comment by gabrielazevedo** [comment]
gabrielazevedo93@gmail.com

**Comment by isaquedias** [comment]
Isaquediasm@gmail.com
Em 06/04/2015 19:30, "Yan Magalhães" <notifications@github.com> escreveu:

**Comment by brunopulis** [comment]
bruno.pulis@gmail.com

**Comment by guilouro** [comment]
guilherme-louro@hotmail.com

**Comment by YanMagale** [comment]
Add ;)


@adrianotosta , @flipggs , @lucasmaiaesilva , @rdiego26  e @willianjusten , precisando do e-mail de vcs pra adicionar la no slack.

**Comment by rdiego26** [comment]
rdiego26@gmail.com

Sds,


"Há grandes homens que fazem com que todos se sintam pequenos. Mas o
verdadeiro grande homem é aquele que faz com que todos se sintam grandes."
(Gilbert Keith Chesterton)
---
Skype: rdiego26
GitHub: rdiego26
Site: www.diegoramos.me

**Comment by willianjusten** [comment]
Caralho, vocês falam demais...não estou tendo tempo gente, mil desculpas...=/
Só li agora (3:44), mas de qualquer forma, willianjustenqui@gmail.com...

**Comment by lucasmaiaesilva** [comment]
lucasmaiaesilva@gmail.com

**Comment by YanMagale** [comment]
Galera, todos que postaram seus e-mails aqui e que estão no grupo, já estão com acesso ao Slack ?

Irei fechar essa issue e continuar esse tópico por lá.

**Comment by rdiego26** [comment]
Yan, vê se me add a pr favor, não recebi nada aqui. =S
rdiego26@gmail.com

Sds,


"Há grandes homens que fazem com que todos se sintam pequenos. Mas o
verdadeiro grande homem é aquele que faz com que todos se sintam grandes."
(Gilbert Keith Chesterton)
---
Skype: rdiego26
GitHub: rdiego26
Site: www.diegoramos.me

**Comment by YanMagale** [comment]
Convite enviado @rdiego26

**Comment by rdiego26** [comment]
Valeu!  :)
Em 02/06/2015 10:50 AM, "Yan Magalhães" <notifications@github.com> escreveu:

**Comment by YanMagale** [comment]
Creio que todos aqui já estejam no slack. Vou criar o tópico lá e fechar essa issue.
